version: '3'
  
services:
   yoti-wordpress-db:
     image: mysql:latest
     ports:
       - "3308:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       MYSQL_PORT: 3306

   wordpress:
     depends_on:
       - yoti-wordpress-db
     build:
       context: ./docker/
       args:
         BRANCH: "SDK-104"
     ports:
       - "7000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: yoti-wordpress-db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

